### ISSUE TITLE
switched font color

### ISSUE THREAD

**Issue by jdrichardsmern** [jdrichardstech/git-intermediate-practice#3]
I switched the font-color to yellow for paragraph. It looks bad. can you fix this?

**Comment by jdrichardstech** [comment]
sure jsrichadrsmern. I will take care of it

**Comment by jdrichardstech** [comment]
i changed font color to goldenrodyellow. check out font-color branch and see what you think.

**Comment by jdrichardsmern** [comment]
looks good. go ahead and create a pull request

**Comment by jdrichardsmern** [comment]
merged successfully
